<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTnAyOPC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTnAyOPC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTnAyOPC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTnAyOPC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTnAyOPC\App_KernelDevDebugContainer([
    'container.build_hash' => 'TnAyOPC',
    'container.build_id' => 'e0843a96',
    'container.build_time' => 1595567665,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTnAyOPC');
